### ISSUE TITLE
UI5 Migrate should return != 0, if files have been modified 

### ISSUE THREAD

**Issue by bkrrrr** [SAP/ui5-migration#209]
This tool would be great to check UI5 apps in Github actions for none recommended code pattern.
The only thing missing, is a return code that lets a ci fail e.g. -1.

![image](https://user-images.githubusercontent.com/14314310/138404769-905af274-5584-4c6e-ad5b-73641c7da0e5.png)

Workaround:
``` yml
name: 'migration'
description: 'see https://www.npmjs.com/package/@ui5/migration'
runs:
  using: "composite"
  steps:
      - name: Install
        run: npm install --global @ui5/migration
        shell: bash
      # see https://github.com/SAP/ui5-migration/issues/209
      - name: run-migration 
        run: | 
          ui5-migration migrate
          echo 'delta<<EOF' >> $GITHUB_ENV
          git diff --color webapp/  >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        shell: bash
      - name: check
        run: echo "${{ env.delta }}"  && exit ${{ env.delta && 1 || 0 }}
        shell: bash
```
